---
- name: Pull MongoDB Docker Image
  docker_image:
    name: "{{ mongodb_image }}"
    source: pull

- name: Run MongoDB Container
  docker_container:
    name: "{{ mongodb_container_name }}"
    image: "{{ mongodb_image }}"
    state: started
    ports:
      - "{{ mongo_port }}:27017"
    networks:
      - name: "{{ app_network }}"
    volumes:
      - "{{ mongo_volume }}:/data/db"
