- name: Ensure gnupg and curl are installed
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
    state: present

- name: Download the MongoDB public GPG key
  ansible.builtin.get_url:
    url: https://www.mongodb.org/static/pgp/server-7.0.asc
    dest: /tmp/mongodb-server-7.0.asc

- name: Import the MongoDB public GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor --batch --yes -o /usr/share/keyrings/mongodb-server-7.0.gpg /tmp/mongodb-server-7.0.asc
  become: yes

- name: Create MongoDB list file
  ansible.builtin.copy:
    content: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
    dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
  become: yes

- name: Reload local package database
  ansible.builtin.apt:
    update_cache: yes

- name: Install MongoDB
  ansible.builtin.apt:
    name: mongodb-org
    state: present

- name: Pin MongoDB packages to prevent unintended upgrades
  ansible.builtin.shell: |
    echo "mongodb-org hold" | sudo dpkg --set-selections
    echo "mongodb-org-database hold" | sudo dpkg --set-selections
    echo "mongodb-org-server hold" | sudo dpkg --set-selections
    echo "mongodb-mongosh hold" | sudo dpkg --set-selections
    echo "mongodb-org-mongos hold" | sudo dpkg --set-selections
    echo "mongodb-org-tools hold" | sudo dpkg --set-selections
  become: yes

- name: Start and enable MongoDB service
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: yes

