---
- name: Create Docker volume for MongoDB
  docker_volume:
    name: "{{ mongo_volume }}"

- name: Run MongoDB container
  docker_container:
    name: mongodb
    image: mongo:latest
    state: started
    restart_policy: always
    ports:
      - "{{ mongo_port }}:27017"
    volumes:
      - "{{ mongo_volume }}:/data/db"
    networks:
      - name: "{{ app_network }}"
