version: '3.3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: yolo-client:1.0.0
    container_name: web
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: yolo-backend:1.0.0
    container_name: API
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/yolomy
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: database_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data: 
    driver: local

networks:
  app-network:
    driver: bridge
