version: '3.8'

services:
  client:
    build:
      context: ./client
    image: mbuguajnr/frontend:v1.0.0
    container_name: client_container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    image: mbuguajnr/backend:v1.0.0
    container_name: backend_container
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongo/yolomy
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data: 
    driver: local

networks:
  app-network:
    driver: bridge
