---
- hosts: all
  become: true
  vars:
    mongo_port: 27017
    backend_port: 5000
    client_port: 3000
    app_network: app-network
    mongo_volume: mongo_data

  roles:
    - role: docker
      tags: docker

    - role: docker_network
      tags: docker_network

    - role: mongodb
      tags: mongodb

    - role: backend
      tags: backend

    - role: client
      tags: client
