---
- name: Pull Backend Docker Image
  docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Run Backend Container
  docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    state: started
    ports:
      - "{{ backend_port }}:5000"
    networks:
      - name: "{{ app_network }}"
