- name: Ensure curl is installed
  apt:
    name: curl
    state: present

- name: Remove existing docker-compose
  file:
    path: /usr/local/bin/docker-compose
    state: absent

- name: Determine the architecture
  set_fact:
    architecture: "{{ ansible_architecture }}"

- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-{{ 'x86_64' if architecture == 'x86_64' else 'aarch64' }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    timeout: 120  # Increase timeout to 120 seconds
  when: architecture in ['x86_64', 'aarch64']


    
