apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
      - name: yolo-backend
        image: gcr.io/yol-omy-ian254/yolo-backend:1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://yolo-mongodb:27017/yolo
