apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-frontend
  template:
    metadata:
      labels:
        app: yolo-frontend
    spec:
      containers:
      - name: yolo-frontend
        image: gcr.io/yol-omy-ian254/yolo-client:1.0.0
        ports:
        - containerPort: 3000
