---
- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
