---
- name: Ensure yolo directory is absent
  file:
    path: /home/vagrant/yolo
    state: absent

- name: Create yolo directory
  file:
    path: /home/vagrant/yolo
    state: directory

- name: Remove existing client container if it exists
  shell: |
    docker rm -f client || true

- name: Pull Client Docker Image
  docker_image:
    name: "{{ frontend_image }}"
    source: pull

- name: Run Client Container
  docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image }}"
    state: started
    ports:
      - "{{ client_port }}:3000"
    networks:
      - name: "{{ app_network }}"
