---
- name: Ensure yolo directory is absent
  file:
    path: /home/vagrant/yolo
    state: absent

- name: Create yolo directory
  file:
    path: /home/vagrant/yolo
    state: directory

- name: Clone the client repository
  git:
    repo: 'https://github.com/your-repo/client.git'
    dest: /home/vagrant/yolo/client

- name: Build and run the client container
  shell: |
    cd /home/vagrant/yolo/client
    docker build -t client .
    docker run -d --name client --network={{ app_network }} -p {{ client_port }}:3000 client
