---
- name: Ensure yolo directory is absent
  file:
    path: /home/vagrant/yolo
    state: absent

- name: Create yolo directory
  file:
    path: /home/vagrant/yolo
    state: directory

- name: Clone the repository
  git:
    repo: 'https://github.com/mbuguajnr23/yolo.git'
    dest: /home/vagrant/yolo/

- name: Build the client image
  docker_image:
    name: client
    source: build
    build:
      path: /home/vagrant/yolo/client
      
- name: Run the client container
  docker_container:
    name: client
    image: client
    state: started
    restart_policy: always
    networks:
      - name: "{{ app_network }}"
    ports:
      - "{{ client_port }}:3000"
